name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
env:
  SECRET_KEY: a-secret-key
  DEBUG: False
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_NAME: django-rest-boilerplate
  DB_USER: hasan
  DB_PASSWORD:
  EMAIL_HOST: localhost
  EMAIL_PORT: 587
  EMAIL_HOST_USER:
  EMAIL_HOST_PASSWORD:
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  FACEBOOK_CLIENT_ID:
  FACEBOOK_CLIENT_SECRET:
  TWITTER_CLIENT_ID:
  TWITTER_CLIENT_SECRET:

jobs:
  deploy_staging:
    environment: staging
    name: 'Deploy to staging'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
        with:
          hosts: '${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            out=$(ls)
            echo $out
