name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
env:
  SECRET_KEY: a-secret-key
  DEBUG: False
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_NAME: django-rest-boilerplate
  DB_USER: hasan
  DB_PASSWORD:
  EMAIL_HOST: localhost
  EMAIL_PORT: 587
  EMAIL_HOST_USER:
  EMAIL_HOST_PASSWORD:
  GOOGLE_CLIENT_ID:
  GOOGLE_CLIENT_SECRET:
  FACEBOOK_CLIENT_ID:
  FACEBOOK_CLIENT_SECRET:
  TWITTER_CLIENT_ID:
  TWITTER_CLIENT_SECRET:
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  TWILIO_FROM: +15005550006
  TWILIO_VERIFY_SERVICE_SID:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
          cache: pip
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: pip install flake8
     
      - name: Run lint
        run: flake8 .
